### ISSUE TITLE
Support for messages targeted at server only

### ISSUE THREAD

**Issue by Makinolo** [GTACOOP-R/GTACoop-R#30]
Currently a client can send a message to another user or to all users if the target user id is 0, but it can happen the client just want to send a message to the server that doesn't need to be broadcast and it's only to change a resource state or other internal operation.
It would be nice to support that

**Comment by Makinolo** [comment]
I've realized this can be achieved by setting args.Cancel to true after processing a message in the resource

**Comment by EntenKoeniq** [comment]
Added
