### ISSUE TITLE
Label userId parameters in functions in a consistent way to disambiguate 

### ISSUE THREAD

**Issue by Makinolo** [GTACOOP-R/GTACoop-R#34]
It's not very clear when we are providing or receiving a player id that is coming from the lidgren id or when it's coming from the player handle.

**Comment by EntenKoeniq** [comment]
XML documentation added (not finished yet).

https://github.com/GTACOOP-R/GTACoop-R/pull/36/commits/33cda5dcfbb31ea3db5f852e36fc71f1d07f5313
